-- MySQL Script generated by MySQL Workbench
-- Mon Apr 20 16:30:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Music_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Music_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Music_store` DEFAULT CHARACTER SET utf8 ;
USE `Music_store` ;

-- -----------------------------------------------------
-- Table `Music_store`.`music_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Music_store`.`music_store` (
  `store_id` INT NOT NULL AUTO_INCREMENT,
  `store_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`store_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Music_store`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Music_store`.`clients` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email_address` VARCHAR(45) NULL,
  `country` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Music_store`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Music_store`.`genre` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Music_store`.`album_ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Music_store`.`album_ratings` (
  `album_ratings_id` INT NOT NULL AUTO_INCREMENT,
  `rating` DECIMAL(4,2) NULL,
  PRIMARY KEY (`album_ratings_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Music_store`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Music_store`.`albums` (
  `album_id` INT NOT NULL AUTO_INCREMENT,
  `genre_id` INT NOT NULL,
  `album_ratings_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `album_name` VARCHAR(45) NOT NULL,
  `label` VARCHAR(45) NOT NULL,
  `product_remaining` INT NOT NULL,
  `item_price` DECIMAL(9,2) NOT NULL,
  `rent_price` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`album_id`),
  INDEX `fk_albums_genre1_idx` (`genre_id` ASC),
  INDEX `fk_albums_album_ratings1_idx` (`album_ratings_id` ASC),
  INDEX `fk_albums_music_store1_idx` (`store_id` ASC),
  CONSTRAINT `fk_albums_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `Music_store`.`genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_albums_album_ratings1`
    FOREIGN KEY (`album_ratings_id`)
    REFERENCES `Music_store`.`album_ratings` (`album_ratings_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_albums_music_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `Music_store`.`music_store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Music_store`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Music_store`.`order_items` (
  `items_id` INT NOT NULL AUTO_INCREMENT,
  `order_date` DATETIME NOT NULL,
  `album_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`items_id`),
  INDEX `fk_order_items_albums1_idx` (`album_id` ASC),
  INDEX `fk_order_items_clients1_idx` (`client_id` ASC),
  CONSTRAINT `fk_order_items_albums1`
    FOREIGN KEY (`album_id`)
    REFERENCES `Music_store`.`albums` (`album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `Music_store`.`clients` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Music_store`.`song_ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Music_store`.`song_ratings` (
  `song_ratings_id` INT NOT NULL AUTO_INCREMENT,
  `rating` DECIMAL(4,2) NULL,
  PRIMARY KEY (`song_ratings_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Music_store`.`song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Music_store`.`song` (
  `song_id` INT NOT NULL AUTO_INCREMENT,
  `album_id` INT NOT NULL,
  `song_ratings_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  `song_name` VARCHAR(45) NOT NULL,
  `singer_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`song_id`),
  INDEX `fk_song_albums1_idx` (`album_id` ASC),
  INDEX `fk_song_song_ratings1_idx` (`song_ratings_id` ASC),
  INDEX `fk_song_genre1_idx` (`genre_id` ASC),
  CONSTRAINT `fk_song_albums1`
    FOREIGN KEY (`album_id`)
    REFERENCES `Music_store`.`albums` (`album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_song_song_ratings1`
    FOREIGN KEY (`song_ratings_id`)
    REFERENCES `Music_store`.`song_ratings` (`song_ratings_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_song_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `Music_store`.`genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Music_store`.`rent_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Music_store`.`rent_items` (
  `rent_id` INT NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `rent_date` DATETIME NOT NULL,
  `album_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `return_date` DATETIME NOT NULL,
  `current_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rent_id`),
  INDEX `fk_rent_items_albums1_idx` (`album_id` ASC),
  INDEX `fk_rent_items_clients1_idx` (`client_id` ASC),
  CONSTRAINT `fk_rent_items_albums1`
    FOREIGN KEY (`album_id`)
    REFERENCES `Music_store`.`albums` (`album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rent_items_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `Music_store`.`clients` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
